# Site settings
title: "Liuwt's blog"
url: "https://Liuwt1997.github.io"
domain: "www.liuwt.com"
github_username: Liuwt1997
github_site_repo: Liuwt1997/Liuwt1997.github.io

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"
