# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.lwt97.com
date_format: "ordinal"
title: 毛茸茸的大水滴
subtitle: "在平坦的道路上曲折前行"
description: "个人博客"
keywords: 毛茸茸的大水滴, Liuwt
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Liuwt
organization: 东北林业大学(NEFU)
organization_url: http://www.nefu.edu.cn
github_username: Liuwt1997
location: Harbin, China
email: liu526754960@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 友情链接

  -
    href: /about/
    label: 关于我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: Liuwt1997/Liuwt1997.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus
#comments_provider: disqus
# !!!重要!!! 请修改下面这些用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#disqus_username: Liuwt

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
